package com.example.neprotest.model

import java.util.*

interface Check {
    val cusname:String
    val cusphone:String
    val numcar:String
    val customerImage: String
    val check1:String
    val check2:String
    val check3:String
    val check4:String
    val check5:String
    val check6:String
    val check7:String
    val check8:String
    val check9:String
    val check10:String
    val check11:String
    val check12:String
    val check13:String
    val check14:String
    val check15:String
    val check16:String
    val check17:String
    val check18:String
    val check19:String
    val check20:String
    val check2_1:String
    val check2_2:String
    val check2_3:String
    val check2_4:String
    val check2_5:String
    val check2_6:String
    val check2_7:String
    val check2_8:String
    val check2_9:String
    val check2_10:String
    val check2_11:String
    val check2_12:String
    val check2_13:String
    val check2_14:String
    val check2_15:String
    val check2_16:String
    val check2_17:String
    val check2_18:String
    val check2_19:String
    val check2_20:String
    val check2_21:String
    val check2_22:String
    val check3_1:String
    val check3_2:String
    val check3_3:String
    val check3_4:String
    val check3_5:String
    val check3_6:String

    val price1:String
    val price2:String
    val price3:String
    val price4:String
    val price5:String
    val price6:String
    val price7:String
    val price8:String
    val price9:String
    val price10:String
    val price11:String
    val price12:String
    val price13:String
    val price14:String
    val price15:String
    val price16:String
    val price17:String
    val price18:String
    val price19:String
    val price20:String
    val price2_1:String
    val price2_2:String
    val price2_3:String
    val price2_4:String
    val price2_5:String
    val price2_6:String
    val price2_7:String
    val price2_8:String
    val price2_9:String
    val price2_10:String
    val price2_11:String
    val price2_12:String
    val price2_13:String
    val price2_14:String
    val price2_15:String
    val price2_16:String
    val price2_17:String
    val price2_18:String
    val price2_19:String
    val price2_20:String
    val price2_21:String
    val price2_22:String
    val price3_1:String
    val price3_2:String
    val price3_3:String
    val price3_4:String
    val price3_5:String
    val price3_6:String


    val total:String
    val totalresidual:String
    val senderId:String
    val recipientId:String
    val senderName:String
    val recipientName:String
    val date: Date

    val editD1:String
    val editD2:String
    val editD3:String
    val editD4:String
    val editD5:String
    val editD6:String
    val editD7:String
    val editD8:String
    val editD9:String
    val pricD1:String
    val pricD2:String
    val pricD3:String
    val pricD4:String
    val pricD5:String
    val pricD6:String
    val pricD7:String
    val pricD8:String
    val pricD9:String

    val cash_paying1:String
    val wallet1:String
    val credit1:String
    val discount1:String
    val receivables1:String
    val cash_price11:String
    val wallet_price1:String
    val credit_price1:String
    val discount_price1:String
    val receivables_price1:String

    val ojor2ed:String
    val ojorm5r6ah:String
    val mjmo3came:String

}